spring:
    mail:
        host: smtp.gmail.com
        username: notefasts0@gmail.com
        password: Fastnotes1!
        port: 587
        protocol: smtp
        properties:
            "mail.transport.protocol": smtp
            "mail.smtp.auth": true
            "mail.smtp.starttls.enable": true


mail:
    tokenEndPoint: "http://localhost:8080/confirm?token="
    MessageUsername: "$username"
    MessageLink: "$link"
    isHtmlContent: true
    pathTemplate: "src/main/resources/static/mail/mailMessage.html"
    subjectMessage: "Confirm email to FASTNOTE app"
    messageTitle: "$subjectMessage"

